/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mytranslator.view.panels;

import java.util.function.Consumer;
import javax.swing.JDialog;
import mytranslator.model.logic.Word;
import mytranslator.view.SwingAttribute;
import mytranslator.view.dialogs.DialogMean;

/**
 *
 * @author Ariel Arnedo
 */
public class PanelViewTranslation extends javax.swing.JPanel implements SwingAttribute{

    private final Word word;
    private final JDialog parent;
    
    public PanelViewTranslation(JDialog parent, Word word) {
        this.parent = parent;
        this.word = word;
        initComponents();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textView = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        botonClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(SwingAttribute.BORDER_SECUNDARY);

        textView.setEditable(false);
        textView.setFont(FONT_TEXT);
        textView.setForeground(COLOR_FOREGROUND);
        textView.setLineWrap(true);
        textView.setTabSize(1);
        textView.setToolTipText("");
        textView.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textView);

        botonClose.setText("Cerrar");
        botonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonClose)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCloseActionPerformed
        ((DialogMean)parent).doClose();
    }//GEN-LAST:event_botonCloseActionPerformed

    private void update(){
        parent.getRootPane().setDefaultButton(botonClose);
        textView.setRows(word.getTranslations().size());
        textView.setColumns(1);
        int row = 0;
        for(String chain : word.getTranslations()){
            textView.append((++row)+": "+chain+"\n");
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea textView;
    // End of variables declaration//GEN-END:variables
}
